# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="规则编码"
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=200, verbose_name="规则名称"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("general", "通用规则"),
                            ("industry", "行业规则"),
                            ("enterprise", "企业规则"),
                        ],
                        max_length=50,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="适用行业"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="规则分类"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                ("rule_content", models.JSONField(verbose_name="规则内容")),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                        ],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("legal_basis", models.TextField(blank=True, verbose_name="法律依据")),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("version", models.IntegerField(default=1, verbose_name="规则版本")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核规则",
                "verbose_name_plural": "审核规则",
                "db_table": "rules_review_rule",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField(verbose_name="合同ID")),
                (
                    "matched_clause",
                    models.TextField(blank=True, verbose_name="匹配的条款"),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="匹配分数",
                    ),
                ),
                (
                    "match_result",
                    models.JSONField(blank=True, null=True, verbose_name="匹配结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "review_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_matches",
                        to="reviews.reviewtask",
                        verbose_name="审核任务",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.reviewrule",
                        verbose_name="规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "规则匹配",
                "verbose_name_plural": "规则匹配",
                "db_table": "rules_rule_match",
                "ordering": ["-match_score"],
            },
        ),
    ]
