# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("version", "版本对比"),
                            ("template", "模板对比"),
                            ("cross_industry", "跨行业对比"),
                        ],
                        max_length=50,
                        verbose_name="对比类型",
                    ),
                ),
                (
                    "source_version",
                    models.IntegerField(blank=True, null=True, verbose_name="源版本号"),
                ),
                (
                    "target_version",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="目标版本号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="对比结果数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "source_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_comparisons",
                        to="contracts.contract",
                        verbose_name="源合同",
                    ),
                ),
                (
                    "target_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_comparisons",
                        to="contracts.contract",
                        verbose_name="目标合同",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.template",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "对比任务",
                "verbose_name_plural": "对比任务",
                "db_table": "comparisons_comparison_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diff_type",
                    models.CharField(
                        choices=[
                            ("added", "新增"),
                            ("deleted", "删除"),
                            ("modified", "修改"),
                        ],
                        max_length=50,
                        verbose_name="差异类型",
                    ),
                ),
                (
                    "diff_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clause", "条款级"),
                            ("field", "字段级"),
                            ("risk", "风险级"),
                        ],
                        max_length=50,
                        verbose_name="差异级别",
                    ),
                ),
                ("source_content", models.TextField(blank=True, verbose_name="源内容")),
                (
                    "target_content",
                    models.TextField(blank=True, verbose_name="目标内容"),
                ),
                (
                    "clause_id",
                    models.CharField(blank=True, max_length=100, verbose_name="条款ID"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                        ],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "comparison_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs",
                        to="comparisons.comparisontask",
                        verbose_name="对比任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "对比差异",
                "verbose_name_plural": "对比差异",
                "db_table": "comparisons_comparison_diff",
                "ordering": ["-risk_level", "created_at"],
            },
        ),
    ]
