# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("clause", "条款推荐"),
                            ("template", "模板推荐"),
                            ("risk_response", "风险应对建议"),
                        ],
                        max_length=50,
                        verbose_name="推荐类型",
                    ),
                ),
                (
                    "recommendation_context",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drafting", "起草中"),
                            ("modifying", "修改中"),
                            ("reviewing", "审核中"),
                            ("negotiating", "谈判中"),
                        ],
                        max_length=50,
                        verbose_name="推荐场景",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="推荐项类型"
                    ),
                ),
                (
                    "item_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="推荐项ID"
                    ),
                ),
                (
                    "item_content",
                    models.TextField(blank=True, verbose_name="推荐项内容"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="推荐分数",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="推荐理由")),
                (
                    "is_accepted",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否被接受"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "推荐记录",
                "verbose_name_plural": "推荐记录",
                "db_table": "recommendations_recommendation",
                "ordering": ["-score", "-created_at"],
            },
        ),
    ]
