# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("party", "合同主体"),
                            ("clause", "条款"),
                            ("regulation", "法规"),
                            ("case", "案例"),
                        ],
                        max_length=50,
                        verbose_name="实体类型",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(max_length=500, verbose_name="实体名称"),
                ),
                (
                    "entity_code",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="实体编码",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="实体描述")),
                (
                    "properties",
                    models.JSONField(blank=True, null=True, verbose_name="实体属性"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="数据来源"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "知识实体",
                "verbose_name_plural": "知识实体",
                "db_table": "knowledge_knowledge_entity",
                "ordering": ["entity_type", "entity_name"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="案例编号"
                    ),
                ),
                (
                    "case_title",
                    models.CharField(max_length=500, verbose_name="案例标题"),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="案例类型"
                    ),
                ),
                (
                    "court",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="审理法院"
                    ),
                ),
                (
                    "judge_date",
                    models.DateField(blank=True, null=True, verbose_name="判决日期"),
                ),
                ("case_summary", models.TextField(blank=True, verbose_name="案例摘要")),
                ("case_content", models.TextField(blank=True, verbose_name="案例内容")),
                (
                    "related_clauses",
                    models.JSONField(blank=True, null=True, verbose_name="相关条款"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.knowledgeentity",
                        verbose_name="关联实体",
                    ),
                ),
            ],
            options={
                "verbose_name": "案例",
                "verbose_name_plural": "案例",
                "db_table": "knowledge_case",
                "ordering": ["-judge_date"],
            },
        ),
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="法规标题")),
                (
                    "regulation_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="法规编号"
                    ),
                ),
                (
                    "regulation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("law", "法律"),
                            ("regulation", "法规"),
                            ("standard", "标准"),
                        ],
                        max_length=50,
                        verbose_name="法规类型",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="发布日期"),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="生效日期"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="失效日期"),
                ),
                ("content", models.TextField(blank=True, verbose_name="法规内容")),
                (
                    "source_url",
                    models.URLField(blank=True, max_length=500, verbose_name="来源URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.knowledgeentity",
                        verbose_name="关联实体",
                    ),
                ),
            ],
            options={
                "verbose_name": "法律法规",
                "verbose_name_plural": "法律法规",
                "db_table": "knowledge_regulation",
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("legal_basis", "法律依据"),
                            ("related_to", "相关于"),
                            ("similar_to", "类似于"),
                        ],
                        max_length=50,
                        verbose_name="关系类型",
                    ),
                ),
                (
                    "relation_properties",
                    models.JSONField(blank=True, null=True, verbose_name="关系属性"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="关系置信度",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="knowledge.knowledgeentity",
                        verbose_name="源实体",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="knowledge.knowledgeentity",
                        verbose_name="目标实体",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识关系",
                "verbose_name_plural": "知识关系",
                "db_table": "knowledge_knowledge_relation",
                "unique_together": {
                    ("source_entity", "target_entity", "relation_type")
                },
            },
        ),
    ]
