# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clauses", "0001_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskIdentification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField(verbose_name="合同ID")),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("invalid", "无效条款"),
                            ("missing", "缺失条款"),
                            ("illegal", "违法条款"),
                            ("non_compliant", "不合规条款"),
                        ],
                        max_length=50,
                        verbose_name="风险类型",
                    ),
                ),
                (
                    "risk_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("legality", "合法性"),
                            ("compliance", "合规性"),
                            ("completeness", "完整性"),
                            ("financial", "财务风险"),
                        ],
                        max_length=50,
                        verbose_name="风险分类",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                        ],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("risk_description", models.TextField(verbose_name="风险描述")),
                (
                    "risk_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="风险位置"
                    ),
                ),
                ("legal_basis", models.TextField(blank=True, verbose_name="法律依据")),
                ("suggestion", models.TextField(blank=True, verbose_name="处理建议")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("handled", "已处理"),
                            ("ignored", "已忽略"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "clause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clauses.contractclause",
                        verbose_name="关联条款",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "review_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="reviews.reviewresult",
                        verbose_name="审核结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险识别",
                "verbose_name_plural": "风险识别",
                "db_table": "risks_risk_identification",
                "ordering": ["-risk_level", "-created_at"],
            },
        ),
    ]
