# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="总体评分",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                        ],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("risk_count", models.IntegerField(default=0, verbose_name="风险数量")),
                ("summary", models.TextField(blank=True, verbose_name="审核摘要")),
                (
                    "report_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="报告文件路径"
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="报告格式"
                    ),
                ),
                (
                    "review_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="详细审核数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_results",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核结果",
                "verbose_name_plural": "审核结果",
                "db_table": "reviews_review_result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause_id",
                    models.CharField(blank=True, max_length=100, verbose_name="条款ID"),
                ),
                (
                    "clause_content",
                    models.TextField(blank=True, verbose_name="条款内容"),
                ),
                (
                    "opinion_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("risk", "风险"),
                            ("suggestion", "建议"),
                            ("warning", "警告"),
                        ],
                        max_length=50,
                        verbose_name="意见类型",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                        ],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("opinion_content", models.TextField(verbose_name="意见内容")),
                ("legal_basis", models.TextField(blank=True, verbose_name="法律依据")),
                ("suggestion", models.TextField(blank=True, verbose_name="修改建议")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "review_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to="reviews.reviewresult",
                        verbose_name="审核结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核意见",
                "verbose_name_plural": "审核意见",
                "db_table": "reviews_review_opinion",
                "ordering": ["-risk_level", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_version",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="合同版本号"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("auto", "自动审核"), ("manual", "人工审核")],
                        default="auto",
                        max_length=50,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Celery任务ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tasks",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核任务",
                "verbose_name_plural": "审核任务",
                "db_table": "reviews_review_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="reviewresult",
            name="review_task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="reviews.reviewtask",
                verbose_name="审核任务",
            ),
        ),
        migrations.CreateModel(
            name="ReviewCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_no", models.IntegerField(verbose_name="循环序号")),
                (
                    "opinion_summary",
                    models.TextField(blank=True, verbose_name="意见汇总"),
                ),
                (
                    "modification_summary",
                    models.TextField(blank=True, verbose_name="修改摘要"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reviewing", "审核中"),
                            ("modifying", "修改中"),
                            ("completed", "已完成"),
                        ],
                        default="reviewing",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="修改时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cycles",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_cycles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_cycles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
                (
                    "review_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reviews.reviewresult",
                        verbose_name="审核结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核闭环",
                "verbose_name_plural": "审核闭环",
                "db_table": "reviews_review_cycle",
                "ordering": ["-cycle_no"],
                "unique_together": {("contract", "cycle_no")},
            },
        ),
    ]
