# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_aimodelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtask',
            name='review_levels',
            field=models.JSONField(
                blank=True,
                help_text='JSON格式，配置需要哪些审核层级，如：["level1", "level3"]',
                null=True,
                verbose_name='审核层级配置'
            ),
        ),
    ]

