# Generated by Django 5.0.1 on 2026-01-04 10:41

import apps.reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_add_review_levels_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="available_models",
            field=models.JSONField(
                default=apps.reviews.models.default_available_models,
                help_text='JSON格式，包含可用模型列表，如：["deepseek-chat", "qwen-plus", "gpt-3.5-turbo"]',
                verbose_name="可用模型列表",
            ),
        ),
    ]
