# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_version",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="合同版本号"
                    ),
                ),
                (
                    "clause_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="条款编号"
                    ),
                ),
                (
                    "clause_type",
                    models.CharField(
                        choices=[
                            ("party", "合同主体"),
                            ("subject", "标的物"),
                            ("period", "履行期限"),
                            ("liability", "违约责任"),
                            ("payment", "付款方式"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="条款类型",
                    ),
                ),
                (
                    "clause_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="条款标题"
                    ),
                ),
                ("clause_content", models.TextField(verbose_name="条款内容")),
                (
                    "start_position",
                    models.IntegerField(blank=True, null=True, verbose_name="起始位置"),
                ),
                (
                    "end_position",
                    models.IntegerField(blank=True, null=True, verbose_name="结束位置"),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="提取的结构化数据"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="识别置信度",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="是否已确认"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同条款",
                "verbose_name_plural": "合同条款",
                "db_table": "clauses_contract_clause",
                "ordering": ["start_position"],
            },
        ),
    ]
