# Generated by Django 5.0.1 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                (
                    "contract_type",
                    models.CharField(max_length=50, verbose_name="合同类型"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="适用行业"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="模板分类"
                    ),
                ),
                ("content", models.TextField(verbose_name="模板内容")),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "tags",
                    models.JSONField(blank=True, null=True, verbose_name="标签列表"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "is_enterprise",
                    models.BooleanField(default=False, verbose_name="是否企业模板"),
                ),
                (
                    "enterprise_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="企业ID"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同模板",
                "verbose_name_plural": "合同模板",
                "db_table": "contracts_template",
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="合同编号"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="合同标题")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("procurement", "采购合同"),
                            ("sales", "销售合同"),
                            ("labor", "劳动合同"),
                            ("service", "服务合同"),
                        ],
                        max_length=50,
                        verbose_name="合同类型",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="所属行业"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("reviewing", "审核中"),
                            ("reviewed", "已审核"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("signed", "已签署"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                (
                    "content",
                    models.JSONField(blank=True, null=True, verbose_name="合同内容"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="合同文件路径"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="文件格式"
                    ),
                ),
                (
                    "current_version",
                    models.IntegerField(default=1, verbose_name="当前版本号"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "drafter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafted_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="起草人",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.template",
                        verbose_name="使用的模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同",
                "verbose_name_plural": "合同",
                "db_table": "contracts_contract",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="版本号")),
                (
                    "content",
                    models.JSONField(blank=True, null=True, verbose_name="版本内容"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="版本文件路径"
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(blank=True, verbose_name="变更摘要"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="变更人",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同版本",
                "verbose_name_plural": "合同版本",
                "db_table": "contracts_contract_version",
                "ordering": ["-version"],
                "unique_together": {("contract", "version")},
            },
        ),
        migrations.CreateModel(
            name="UserHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habit_type",
                    models.CharField(
                        choices=[
                            ("clause_preference", "条款偏好"),
                            ("template_preference", "模板偏好"),
                        ],
                        max_length=50,
                        verbose_name="习惯类型",
                    ),
                ),
                ("habit_key", models.CharField(max_length=200, verbose_name="习惯键")),
                (
                    "habit_value",
                    models.JSONField(blank=True, null=True, verbose_name="习惯值"),
                ),
                ("frequency", models.IntegerField(default=1, verbose_name="使用频率")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户习惯",
                "verbose_name_plural": "用户习惯",
                "db_table": "contracts_user_habit",
                "unique_together": {("user", "habit_type", "habit_key")},
            },
        ),
    ]
